document_analysis:
  description: >
  
      Retrieve and analyze all available project documents (project brief, kickoff meeting transcripts, requirements docs, etc.). 
      Identify key information including project goals, requirements, constraints, stakeholders, and timelines tailored for the project {domain}.
      Highlight any inconsistencies or gaps between documents, creating a list of items needing clarification.
      Share an initial summary of your understanding and identify 3-5 key clarification questions to begin the collaborative process.
  
  expected_output: >
    detailed analysis, summary pf the prject scope details, and clarification questions
  agent: business_analyst

scope_development:
  description: >
    Based on the template provided in the reference document, 
    break down the scope document creation into logical sections 
    (Executive Summary, Project Objectives, Scope Definition, etc.).
    For each section:
      1. Draft content based on available information
      2. Proactively make recommendations where information is incomplete
      3. Clearly mark assumptions you've made that require validation
      4. Present each section to the user for feedback
      5. Explicitly ask specific questions about unclear items
      6. Incorporate feedback before moving to the next section
      7. Provide only hiogh level informatuion about the technical aspects based on the information you handled
      so far on the project as it will be handled by the technical lead. 
      
      Present conflicts between source documents clearly, 
      explaining the nature of each conflict and requesting user guidance on resolution.
      Once all sections have received user feedback and approval, compile them into a final comprehensive scope document.
      Present the complete document to the user for final review.
      Highlight areas where your industry expertise suggests potential risks or opportunities that may not be explicitly addressed.
      After final user approval, format the document according to the provided output standards.


  expected_output: >
    Final approved scope document compoenets according to the provided output standards.
  agent: business_analyst
  
technical_sections_expansion:
  description: >
    Review the scope components retrived from the business analyst agent,  
    and expand on the all the technical specifications making sure that architecture recommendations and resource requirements are clearly defined.
    Provide feedback on the technical feasibility of the proposed solutions, 
    and finalize parts like the scope based on the infoirmation provided in the components and based on user input when there are multiple options. 
    Identify any potential risks or challenges that may arise during implementation.
   
    Focus on the following items when providing technical expansion:
      - ScopeDefinition and its components
      - TechnicalChallenge
      - Constraints (specifically technical constraints)
      - The TechnicalImplementation elements
      - Team Structure and Resources
      - Dependencies
      - any additional suggestions on the RiskAssessment
    
      Create a list of technical clarification questions needed before providing detailed recommendations.
      Share an initial assessment of the technical aspects of the project and present your clarification questions to the user.
      Once cleared present the final scope compoenets along with the updated scope sections.
  
  expected_output: Final scope document with all its components and the technical sections expanded and clarified in the standards provided.
  agent: technical_lead_scope_specialist

review_and_approval:
  description: >
    - Aggregate the information and provided by the business analyst agent and the technical lead.
    - Present the final scope document to the user for review.
    - Highlight areas where your industry expertise suggests potential risks or opportunities that may not be explicitly addressed.
    - Provide a summary of the key points and recommendations for the user to consider.
    - Clearly outline any assumptions made during the analysis and development process.
  expected_output: >
    Final scope document with all its components and the technical sections expanded and clarified in the standards provided.

  agent: chief_product_officer

roadmap_development:
  description: >
    Based on the final approved scope document, 
    develop a detailed project roadmap that outlines key milestones, deliverables, and timelines.
    Ensure that the roadmap aligns with the project goals and objectives, 
    and provides a clear path for successful project
  expected_output: >
    Project roadmap with key milestones and timelines in the standards provided.

  agent: product_manager